analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    duplicate_ignore: ignore

custom_lint:
  rules:
    - prefer_const_constructors: true
    - prefer_const_declarations: true
