include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    duplicate_ignore: ignore
    curly_braces_in_flow_control_structures: ignore
